version: "3.8"

services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    image: xiaopeng163/flask-redis:latest
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PASS=${REDIS_PASSWORD}
    networks:
      - mynet

  redis-server:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - mynet

networks:
  mynet:
